### ISSUE TITLE
Monova crawler issues

### ISSUE THREAD

**Issue by skwerlman** [sergiotapia/magnetissimo#116]
While adding NSFW filtering, I noticed that the Monova crawler wasn't actually scraping any torrents.

This is because the URL format for torrent info pages has changed to look like `//monova.org/DC03ED592535887EC423D3EAABC7F17782C47706`.

However, even after fixing that issue, the crawler currently crashes when trying to parse any torrent info page, producing this error:

```
[error] GenServer #PID<0.479.0> terminating
** (FunctionClauseError) no function clause matching in Floki.HTMLTree.build/1
    (floki) lib/floki/html_tree.ex:14: Floki.HTMLTree.build({:ok, "\n<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\" />\n<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\n<meta name=\"description\" content=\"Download Microsoft Office Professional Plus 2013 x86 PT-BR + Ativador Torrent\" />\n<meta name=\"author\" content=\"monova.org\" />\n<link rel=\"shortcut icon\" href=\"data:image/png;base64,AAABAAEAEBAAAAEAIABoBAAAFgAAACgAAAAQAAAAIAAAAAEAIAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAD18/EOnYJppXVUNPdxUDD/cE4u/25MK/9sSin/a0gn/2lGJf9nRCP/ZkIh/2RAHv9iPhz/ZUMg95uBZ6X18/EOnoVsoYdvWf+Nemj/iHVi/4RvXP+BbFr/e2RQ/3ZfSv9xWkT/bVZB/2hPOP9kSjL/X0Qs/1o/Jv9ZOx//nIJpo3FNKfWNb1H/qZJ7/6mSfP9+XT3/dlc6/6iRe/+pkXv/qZN8/25NLv92VDP/qZJ8/6mSe/+eg2r/Xj4f/2VDIfd2UzL/s56K////////////moBn/4VnSv////////////////+Qc1j/g2VI////////////4trS/2FBI/9iPh3/fl4//6SMdf///////////5+Gbf+dhGv/////////////////vaya/3tYN////////////+Lb0/9kRSf/ZEEf/4JjRv+cgmn///////////+mjnf/u6mX/////////////////+zn4v90Tyv////////////k3db/Z0gr/2ZDI\r\n    v+EZkn/l3xi////////////rpmE/9vSyP//////////////////////i2xN////////////5+Ha/2pLLv9oRST/h2lM/5N3Xf///////////7qnlf/5+Pb//////+jh2/////7//////6+Zhf/+/v7//////+vm4P9sTTD/aUcm/4lsT/+QdFn////////////d1Mv////////////Ftqf/6+bh///////OwbT//fz8///////v6+b/bk8y/2tJKf+Mb1P/kXZc//z7+v///////Pz7////////////qpR+/7+unf//////7urm//v6+f//////8/Dt/3BRM/9tSyv/jnJW/5mAZ//08e7//////////////////////5B0Wf+TeF3///////////////7///////j29P9yUjT/b04u/5F1Wf+jjXf/6uXf//////////////////f18/+FaU3/hWlO//Ds6P/////////////////8+/r/dVU3/3FQMP+TeF3/rpuI/+La0v/////////////////YzsT/mIFs/56Mev/BsKD//////////////////v79/3laPP9zUjL/lHhc87qqmv+qlH7/v66d/7+unf+/rp3/noRr/6ubi/+0qZ7/jW9\r\n    R/7+unv+/rp3/v66d/8Cvnv95WTv/eFc49aOLc5zDtab/yb2x/8S3qv+/saT/uaqc/7OjlP/Bt67/vbOp/6eWhv+ei3n/mYVy/5R/bP+Qemb/g2lQ/6CHb5/39vQKo4tzm45xU/CNcFP6i25Q+olrTvqHaUv6hWZI+oJkRfqBYkL6f19B+n1dPvp7Wjv6fFs88KGIcJz49vQKgAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAEAAA==\" />\n<meta name=\"msvalidate.01\" content=\"EC6001F9520C26011A33D9D4CACB2A41\" />\n<link rel=\"alternate\" hreflang=\"x-default\" href=\"//www.monova.org/0F75DFE7E2794E542D7AA8225476306A299AAED3\">\n<link rel=\"alternate\" hreflang=\"it\" href=\"//it.monova.org/0F75DFE7E2794E542D7AA8225476306A299AAED3\" />\n<link rel=\"alternate\" hreflang=\"ru\" href=\"//ru.monova.org/0F75DFE7E2794E542D7AA8225476306A299AAED3\" />\n<link rel=\"canonical\" href=\"https://monova.org/torrent/0F75DFE7E2794E542D7AA8225476306A299AAED3\" />\n<link rel=\"canonical\" href=\"https://monova.org/details/0F75DFE7E2794E542D7AA8225476306A299AAED3\" />\n<title>Microsoft Office Professional Plus 2013 x86 PT-BR + Ativador - Torrent</title>\n<link href=\"https://fonts.googleapis.com/icon?family=Material+Icons\" rel=\"stylesheet\">\n<link href=\"//monova.org/css/materialize.css\" rel=\"stylesheet\" />\n<link href=\"//monova.org/css/style-v2.css?v=1.6\" rel=\"stylesheet\" />\n<style>\r\n            .FYkyqZjiIQCUtdS{\r\n                width: 200px;\r\n                height: 54px;\r\n                cursor: pointer;\r\n                padding: 0 2rem;\r\n                font-size: 20px;\r\n                line-height: 56px;\r\n                color:#fff !important;\r\n                background-color: #5CB85C;\r\n                display: block;\r\n                position: fixed;\r\n                left: 0px;\r\n                top: 0px;\r\n                text-align: center;\r\n                border: none;\r\n                border-radius: 5px;\r\n                font-weight: 400;\r\n                white-space: nowrap;\r\n                vertical-align: middle;\r\n                text-transform: uppercase;\r\n            }\r\n            \r\n                            .BKswfJHCjcyEuV{\r\n                    width: 400px;\r\n                }\r\n                \r\n                .iJsAKkm{\r\n                    width: 80px;\r\n                    margin-left: 405px;\r\n                    font-size: 1.6rem;\r\n                }\r\n            \r\n            .BKswfJHCjcyEuV:hover,\r\n            .iJsAKkm:hover{\r\n                color: #fff;\r\n                background-color: #5CB85C !important;\r\n                border-color: #398439;\r\n            }\r\n    " <> ...})
    (floki) lib/floki/finder.ex:47: Floki.Finder.find_selectors/2
    (floki) lib/floki.ex:192: Floki.find/2
    (magnetissimo) lib/magnetissimo/crawler/monova.ex:86: Magnetissimo.Crawler.Monova.torrent_information/1
    (magnetissimo) lib/magnetissimo/crawler/monova.ex:59: Magnetissimo.Crawler.Monova.process/2
    (magnetissimo) lib/magnetissimo/crawler/monova.ex:33: Magnetissimo.Crawler.Monova.handle_info/2
    (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: :work
State: {[torrent_link: "https://monova.org/7B4FD55FDD099267B8B74996E0278558F30D0D43", torrent_link: "https://monova.org/551FBBFF4E09B20D9A33E8FBBFDF70091795563C", torrent_link: "https://monova.org/B46AF33C3647B2BB0D62D4EBEF377753543AD96F", torrent_link: "https://monova.org/3937BADF3F90437AC08970F7978084BE4240B98E", torrent_link: "https://monova.org/6BB3639DA6DF1DA84F02B9D208AE2D4F791F119B", torrent_link: "https://monova.org/B9C0CFD81C8059C2E84A5C81291B1F151A82ED6F", torrent_link: "https://monova.org/DC03ED592535887EC423D3EAABC7F17782C47706", torrent_link: "https://monova.org/7E08E8303CF5B45198C070E1722B9134FEFEA60E", torrent_link: "https://monova.org/0DDF909A21B2A893608BBEB00BDD38254D2FB20C", torrent_link: "https://monova.org/75446DDF0F9AEBD69EE78D1AE0BD7388C0BD5A88", torrent_link: "https://monova.org/67FC384C8DE4D86DCECFBCAEB2FBFCFB82F9AE7B", torrent_link: "https://monova.org/BA201C2CD5246318C6CCA51854C091B311D9F1BE", torrent_link: "https://monova.org/B76DC1A4B8B4B59111A6E85561B0C434B4E3AA89", torrent_link: "https://monova.org/5417A8DEC3A34A7D2891709A31DE7F8A39BC23ED", torrent_link: "https://monova.org/5F3851D2F610ADE8301C4EF155AAAC1F0D080962", torrent_link: "https://monova.org/C1AA96C866E71DC32C12DA1601A2AE069223E093", torrent_link: "https://monova.org/87AA3D592DE9DEA0F8972D4A52850C6AC4BCA059", torrent_link: "https://monova.org/9BE90B843AD174A57ED9EB97FDE563D4B1E6B71D", torrent_link: "https://monova.org/2042C27991AF8744B0331A1A8ED852330A64DBD5", torrent_link: "https://monova.org/289E46DCDA7151CD53F04DDB6135497855411C05", torrent_link: "https://monova.org/483947D439805047AAB476BB64A1BF5B390933B7", torrent_link: "https://monova.org/4EFB48F792BE82424AE9100B13333E1C2DB75A26", torrent_link: "https://monova.org/135620D3BC26B44F517E07F46BE4E172661A0946", torrent_link: "https://monova.org/5D3ACC001BF7874081C660B1C42322A6C7478137", torrent_link: "https://monova.org/5D73012FB6AE2646F0D85A6AE6CFB26B31CF3AB1", torrent_link: "https://monova.org/5D73012FB6AE2646F0D85A6AE6CFB26B31CF3AB1", torrent_link: "https://monova.org/EDABDDC6D04D726448CCB39F5DC796B321405BA8", torrent_link: "https://monova.org/06FEA83FF3983C4F59EF39763810DB27FA0C766C", torrent_link: "https://monova.org/E1630043AD75975ECE9F5EEA6AAFDF57C010BA47", torrent_link: "https://monova.org/E578D6770BBC883ADC55381940F388E71ECC77A0", torrent_link: "https://monova.org/44AC1123D9FC17BFFBCDE900F45C2561B4CB0215", torrent_link: "https://monova.org/6E95802F261168001C6AB22910880A737BA78897", torrent_link: "https://monova.org/19871F4C301E2BDB33390BDC7303FD145DE95B82", torrent_link: "https://monova.org/C703D48493C4F1420A2ADF5F43468C72A035A31E", torrent_link: "https://monova.org/CAAE05A146726E01FDBA6B012741D44DDE9E8C01", torrent_link: "https://monova.org/C0FBF1DA67B46868CB263F7EE87B03DDC53EB3AA", torrent_link: "https://monova.org/F842F9510FFDE18E90F5D1A8B2A4F2C7FC87645E", torrent_link: "https://monova.org/3CC816DD6B1300ACAA5D9D6C8B0419BE7ECFC701", torrent_link: "https://monova.org/A88657975E898F3832385912F4A5E9E055957A0C", torrent_link: "ht (truncated)
```

Additionally, there's a logic error which causes the 30 minute wait between runs to occur before the first run as well. This also happens with a couple other crawlers such as xBit.

**Comment by pahakalle** [comment]
Seems like they added the hash of the torrent to the link

**Comment by tchoutri** [comment]
Yup', a bad behaviour is happening here: [monova.ex#L86](https://github.com/sergiotapia/magnetissimo/blob/master/lib/magnetissimo/crawler/monova.ex#L86).  
That would require to refactor the module.

**Comment by pahakalle** [comment]
Monova's site still looks unfinished to me so they might make some bigger changes at some point

**Comment by tchoutri** [comment]
Indeed.
Let us not activate it for the moment.
