### ISSUE TITLE
TLS Client error 

### ISSUE THREAD

**Issue by fallenczar** [sergiotapia/magnetissimo#133]
```
Webpack is watching the filesâ¦

Hash: 14377042d3bf4cebbd52
Version: webpack 4.4.0
Time: 1715ms
Built at: 7/22/2019 2:03:03 AM
                          Asset       Size       Chunks             Chunk Names
                 ../css/app.css    206 KiB  ./js/app.js  [emitted]  ./js/app.js
                         app.js    7.3 KiB  ./js/app.js  [emitted]  ./js/app.js
                 ../favicon.ico   1.23 KiB               [emitted]  
                  ../robots.txt  202 bytes               [emitted]  
../images/magnetissimo-logo.jpg   15.2 KiB               [emitted]  
          ../images/phoenix.png   13.6 KiB               [emitted]  
      ../images/magnet-icon.png   37.9 KiB               [emitted]  
[../../../deps/phoenix_html/priv/static/phoenix_html.js] /opt/magnetissimo/deps/phoenix_html/priv/static/phoenix_html.js 2.17 KiB {./js/app.js} [built]
[./css/app.css] 39 bytes {./js/app.js} [built]
[./js/app.js] 493 bytes {./js/app.js} [built]
   [0] multi ./js/app.js 28 bytes {./js/app.js} [built]
    + 2 hidden modules
Child mini-css-extract-plugin node_modules/css-loader/index.js!css/app.css:
    [./node_modules/css-loader/index.js!./css/app.css] ./node_modules/css-loader!./css/app.css 413 bytes {mini-css-extract-plugin} [built]
    [./node_modules/css-loader/index.js!./css/bulma.css] ./node_modules/css-loader!./css/bulma.css 216 KiB {mini-css-extract-plugin} [built]
        + 1 hidden module
[info] GET /
[debug] Processing with MagnetissimoWeb.PageController.index/2
  Parameters: %{}
  Pipelines: [:browser]
[debug] QUERY OK source="torrents" db=1.1ms decode=3.8ms queue=1.8ms
SELECT count('*') FROM "torrents" AS t0 []
[debug] QUERY OK source="torrents" db=1.1ms queue=1.6ms
SELECT t0."id", t0."magnet_url", t0."name", t0."canonical_url", t0."website_source", t0."leechers", t0."seeds", t0."size", t0."published_at", t0."inserted_at", t0."updated_at" FROM "torrents" AS t0 ORDER BY t0."inserted_at" DESC LIMIT $1 OFFSET $2 [50, 0]
[debug] QUERY OK source="torrents" db=1.3ms queue=1.5ms
SELECT t0."website_source", count(t0."id") FROM "torrents" AS t0 GROUP BY t0."website_source" ORDER BY t0."website_source" []
[debug] QUERY OK source="torrents" db=0.9ms queue=1.0ms
SELECT count(t0."id") FROM "torrents" AS t0 []
[info] Sent 200 in 134ms
[info] Replied phoenix:live_reload :ok
[info] GET /
[debug] Processing with MagnetissimoWeb.PageController.index/2
  Parameters: %{}
  Pipelines: [:browser]
[debug] QUERY OK source="torrents" db=2.1ms
SELECT count('*') FROM "torrents" AS t0 []
[debug] QUERY OK source="torrents" db=2.3ms
SELECT t0."id", t0."magnet_url", t0."name", t0."canonical_url", t0."website_source", t0."leechers", t0."seeds", t0."size", t0."published_at", t0."inserted_at", t0."updated_at" FROM "torrents" AS t0 ORDER BY t0."inserted_at" DESC LIMIT $1 OFFSET $2 [50, 0]
[debug] QUERY OK source="torrents" db=1.6ms
SELECT t0."website_source", count(t0."id") FROM "torrents" AS t0 GROUP BY t0."website_source" ORDER BY t0."website_source" []
[debug] QUERY OK source="torrents" db=1.8ms
SELECT count(t0."id") FROM "torrents" AS t0 []
[info] Sent 200 in 9ms
[info] Replied phoenix:live_reload :ok
[info] GET /
[debug] Processing with MagnetissimoWeb.PageController.index/2
  Parameters: %{}
  Pipelines: [:browser]
[debug] QUERY OK source="torrents" db=0.3ms
SELECT count('*') FROM "torrents" AS t0 []
[debug] QUERY OK source="torrents" db=0.4ms
SELECT t0."id", t0."magnet_url", t0."name", t0."canonical_url", t0."website_source", t0."leechers", t0."seeds", t0."size", t0."published_at", t0."inserted_at", t0."updated_at" FROM "torrents" AS t0 ORDER BY t0."inserted_at" DESC LIMIT $1 OFFSET $2 [50, 0]
[debug] QUERY OK source="torrents" db=0.2ms
SELECT t0."website_source", count(t0."id") FROM "torrents" AS t0 GROUP BY t0."website_source" ORDER BY t0."website_source" []
[debug] QUERY OK source="torrents" db=0.2ms
SELECT count(t0."id") FROM "torrents" AS t0 []
[info] Sent 200 in 2ms
[info] Replied phoenix:live_reload :ok
[info] GET /
[debug] Processing with MagnetissimoWeb.PageController.index/2
  Parameters: %{}
  Pipelines: [:browser]
[debug] QUERY OK source="torrents" db=2.1ms
SELECT count('*') FROM "torrents" AS t0 []
[debug] QUERY OK source="torrents" db=2.3ms
SELECT t0."id", t0."magnet_url", t0."name", t0."canonical_url", t0."website_source", t0."leechers", t0."seeds", t0."size", t0."published_at", t0."inserted_at", t0."updated_at" FROM "torrents" AS t0 ORDER BY t0."inserted_at" DESC LIMIT $1 OFFSET $2 [50, 0]
[debug] QUERY OK source="torrents" db=1.2ms
SELECT t0."website_source", count(t0."id") FROM "torrents" AS t0 GROUP BY t0."website_source" ORDER BY t0."website_source" []
[debug] QUERY OK source="torrents" db=0.8ms
SELECT count(t0."id") FROM "torrents" AS t0 []
[info] Sent 200 in 7ms
[info] Replied phoenix:live_reload :ok
[debug] [TorrentDownloads] Downloading url: https://www.torrentdownloads.me/rss.xml?type=today
[debug] [EZTV] Downloading url: https://eztv.io/ezrss.xml
[debug] [YTS.am] Downloading url: https://yts.am/rss
[debug] [ThePirateBay] Downloading url: https://thepiratebay.org/rss//top100/0
[debug] [Nyaa] Downloading url: https://nyaa.si/?page=rss
[debug] [NyaaPantsu] Downloading url: https://nyaa.pantsu.cat/feed
[info] TLS client: In state hello received SERVER ALERT: Fatal - Illegal Parameter

[info] TLS client: In state hello received SERVER ALERT: Fatal - Illegal Parameter

[info] TLS client: In state hello received SERVER ALERT: Fatal - Illegal Parameter

[info] TLS client: In state hello received SERVER ALERT: Fatal - Illegal Parameter

[error] GenServer Magnetissimo.Crawlers.EZTV terminating
** (HTTPoison.Error) {:tls_alert, {:illegal_parameter, 'TLS client: In state hello received SERVER ALERT: Fatal - Illegal Parameter\n'}}
    (httpoison) lib/httpoison.ex:128: HTTPoison.request!/5
    (magnetissimo) lib/crawlers/EZTV.ex:66: Magnetissimo.Crawlers.EZTV.rss/0
    (magnetissimo) lib/crawlers/EZTV.ex:17: Magnetissimo.Crawlers.EZTV.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: :rss_fetch
State: []
[error] GenServer Magnetissimo.Crawlers.YTS terminating
** (HTTPoison.Error) {:tls_alert, {:illegal_parameter, 'TLS client: In state hello received SERVER ALERT: Fatal - Illegal Parameter\n'}}
    (httpoison) lib/httpoison.ex:128: HTTPoison.request!/5
    (magnetissimo) lib/crawlers/YTS.ex:62: Magnetissimo.Crawlers.YTS.rss/0
    (magnetissimo) lib/crawlers/YTS.ex:17: Magnetissimo.Crawlers.YTS.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: :rss_fetch
State: []
[error] GenServer Magnetissimo.Crawlers.TorrentDownloads terminating
** (HTTPoison.Error) {:tls_alert, {:illegal_parameter, 'TLS client: In state hello received SERVER ALERT: Fatal - Illegal Parameter\n'}}
    (httpoison) lib/httpoison.ex:128: HTTPoison.request!/5
    (magnetissimo) lib/crawlers/TorrentDownloads.ex:72: Magnetissimo.Crawlers.TorrentDownloads.rss/0
    (magnetissimo) lib/crawlers/TorrentDownloads.ex:17: Magnetissimo.Crawlers.TorrentDownloads.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: :rss_fetch
State: []
[error] GenServer Magnetissimo.Crawlers.ThePirateBay terminating
** (HTTPoison.Error) {:tls_alert, {:illegal_parameter, 'TLS client: In state hello received SERVER ALERT: Fatal - Illegal Parameter\n'}}
    (httpoison) lib/httpoison.ex:128: HTTPoison.request!/5
    (magnetissimo) lib/crawlers/ThePirateBay.ex:62: Magnetissimo.Crawlers.ThePirateBay.rss/0
    (magnetissimo) lib/crawlers/ThePirateBay.ex:17: Magnetissimo.Crawlers.ThePirateBay.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: :rss_fetch
State: []
[info] Application magnetissimo exited: shutdown
[info] GET /
[debug] Processing with MagnetissimoWeb.PageController.index/2
  Parameters: %{}
  Pipelines: [:browser]
[info] Sent 500 in 48ms
[error] #PID<0.559.0> running MagnetissimoWeb.Endpoint (connection #PID<0.558.0>, stream id 1) terminated
Server: 192.168.1.100:56056 (http)
Request: GET /
** (exit) an exception was raised:
    ** (RuntimeError) could not lookup Magnetissimo.Repo because it was not started or it does not exist
        (ecto) lib/ecto/repo/registry.ex:18: Ecto.Repo.Registry.lookup/1
        (ecto) lib/ecto/repo/queryable.ex:131: Ecto.Repo.Queryable.execute/4
        (ecto) lib/ecto/repo/queryable.ex:18: Ecto.Repo.Queryable.all/3
        (ecto) lib/ecto/repo/queryable.ex:66: Ecto.Repo.Queryable.one/3
        (scrivener_ecto) lib/scrivener/paginater/ecto/query.ex:46: Scrivener.Paginater.Ecto.Query.total_entries/3
        (scrivener_ecto) lib/scrivener/paginater/ecto/query.ex:17: Scrivener.Paginater.Ecto.Query.paginate/2
        (magnetissimo_web) lib/magnetissimo_web/controllers/page_controller.ex:5: MagnetissimoWeb.PageController.index/2
        (magnetissimo_web) lib/magnetissimo_web/controllers/page_controller.ex:1: MagnetissimoWeb.PageController.action/2
        (magnetissimo_web) lib/magnetissimo_web/controllers/page_controller.ex:1: MagnetissimoWeb.PageController.phoenix_controller_pipeline/2
        (magnetissimo_web) lib/magnetissimo_web/endpoint.ex:1: MagnetissimoWeb.Endpoint.instrument/4
        (phoenix) lib/phoenix/router.ex:275: Phoenix.Router.__call__/1
        (magnetissimo_web) lib/magnetissimo_web/endpoint.ex:1: MagnetissimoWeb.Endpoint.plug_builder_call/2
        (magnetissimo_web) lib/plug/debugger.ex:122: MagnetissimoWeb.Endpoint."call (overridable 3)"/2
        (magnetissimo_web) lib/magnetissimo_web/endpoint.ex:1: MagnetissimoWeb.Endpoint.call/2
        (phoenix) lib/phoenix/endpoint/cowboy2_handler.ex:33: Phoenix.Endpoint.Cowboy2Handler.init/2
        (cowboy) /opt/magnetissimo/deps/cowboy/src/cowboy_handler.erl:41: :cowboy_handler.execute/2
        (cowboy) /opt/magnetissimo/deps/cowboy/src/cowboy_stream_h.erl:296: :cowboy_stream_h.execute/3
        (cowboy) /opt/magnetissimo/deps/cowboy/src/cowboy_stream_h.erl:274: :cowboy_stream_h.request_process/3
        (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
[info] Replied phoenix:live_reload :ok
```

**Comment by skwerlman** [comment]
what versions of elixir and erlang are you using? this looks like a broken TLS implementation to me

**Comment by fallenczar** [comment]
Ubuntu 19.04 
```
esl-erlang is already the newest version (1:22.0.7-1).
elixir is already the newest version (1.9.1-1).
```

Thank you for your help

**Comment by skwerlman** [comment]
some things to try:
- check that libssl is the newest available (currently 1.1.1b-ubuntu2.4)
- downgrade to a previous libssl
  - the esl-erlang deb claims it works with libssl1.1 but doesn't specify a version range beyond that
- downgrade to OTP 22.0.5; some changes to the ssl lib (havent checked which) were added in 22.0.6
- downgrade to OTP 21.3
- downgrade to elixir 1.8
- build erlang/elixir yourself (last ditch only imo)

**Comment by fallenczar** [comment]
i built erlang/elixir from source, unfortunately that did not fix the problem.

**Comment by Ermolaev-Nikolay** [comment]
What is the result? What's wrong?

**Comment by sergiotapia** [comment]
I'm closing this stale issue. Please open a new ticket if this is still happening. The new liveview-rewrite branch has a Dockerfile that will make it easier for anyone who wants to run this.
