### ISSUE TITLE
HTTPoison.Error Application magnetissimo exited: shutdown

### ISSUE THREAD

**Issue by Ermolaev-Nikolay** [sergiotapia/magnetissimo#134]
I followed those instructions. 
```[info] Running MagnetissimoWeb.Endpoint with cowboy 2.6.1 at http://localhost:4000
[debug] [EZTV] Downloading url: https://eztv.io/ezrss.xml
[debug] [ThePirateBay] Downloading url: https://thepiratebay.org/rss//top100/0
[debug] [TorrentDownloads] Downloading url: https://www.torrentdownloads.me/rss.xml?type=today
[debug] [Nyaa] Downloading url: https://nyaa.si/?page=rss
[debug] [NyaaPantsu] Downloading url: https://nyaa.pantsu.cat/feed
[debug] [YTS.am] Downloading url: https://yts.am/rss
[debug] [leetx] Downloading url: https://1337x.to/cat/Anime/1/
[error] GenServer Magnetissimo.Crawlers.EZTV terminating
** (HTTPoison.Error) {:option, :server_only, :honor_cipher_order}
    (httpoison) lib/httpoison.ex:128: HTTPoison.request!/5
    (magnetissimo) lib/crawlers/EZTV.ex:66: Magnetissimo.Crawlers.EZTV.rss/0
    (magnetissimo) lib/crawlers/EZTV.ex:17: Magnetissimo.Crawlers.EZTV.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: :rss_fetch
State: []
[error] GenServer Magnetissimo.Crawlers.NyaaPantsu terminating
** (HTTPoison.Error) {:option, :server_only, :honor_cipher_order}
    (httpoison) lib/httpoison.ex:128: HTTPoison.request!/5
    (magnetissimo) lib/crawlers/NyaaPantsu.ex:62: Magnetissimo.Crawlers.NyaaPantsu.rss/0
    (magnetissimo) lib/crawlers/NyaaPantsu.ex:17: Magnetissimo.Crawlers.NyaaPantsu.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: :rss_fetch
State: []
[error] GenServer Magnetissimo.Crawlers.Nyaa terminating
** (HTTPoison.Error) {:option, :server_only, :honor_cipher_order}
    (httpoison) lib/httpoison.ex:128: HTTPoison.request!/5
    (magnetissimo) lib/crawlers/Nyaa.ex:67: Magnetissimo.Crawlers.Nyaa.rss/0
    (magnetissimo) lib/crawlers/Nyaa.ex:17: Magnetissimo.Crawlers.Nyaa.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: :rss_fetch
State: []
[error] GenServer Magnetissimo.Crawlers.ThePirateBay terminating
** (HTTPoison.Error) {:option, :server_only, :honor_cipher_order}
    (httpoison) lib/httpoison.ex:128: HTTPoison.request!/5
    (magnetissimo) lib/crawlers/ThePirateBay.ex:62: Magnetissimo.Crawlers.ThePirateBay.rss/0
    (magnetissimo) lib/crawlers/ThePirateBay.ex:17: Magnetissimo.Crawlers.ThePirateBay.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: :rss_fetch
State: []
[error] GenServer Magnetissimo.Crawlers.TorrentDownloads terminating
** (HTTPoison.Error) {:option, :server_only, :honor_cipher_order}
    (httpoison) lib/httpoison.ex:128: HTTPoison.request!/5
    (magnetissimo) lib/crawlers/TorrentDownloads.ex:72: Magnetissimo.Crawlers.TorrentDownloads.rss/0
    (magnetissimo) lib/crawlers/TorrentDownloads.ex:17: Magnetissimo.Crawlers.TorrentDownloads.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: :rss_fetch
State: []
[info] Application magnetissimo exited: shutdown
```
OS: Ubuntu 19.04
```mix --version
Erlang/OTP 22 [erts-10.5.3] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:1]

Mix 1.9.2 (compiled with Erlang/OTP 21)
```
What was a mistake?

**Comment by Ermolaev-Nikolay** [comment]
The [solution](https://github.com/edgurgel/httpoison/issues/393) for this case.

**Comment by tchoutri** [comment]
Thank you :)
