### ISSUE TITLE
Could not lookup Magnetissimo.Repo because it was not started or it does not exist

### ISSUE THREAD

**Issue by sxiii** [sergiotapia/magnetissimo#135]
Hi! I'm trying to use the following instructions:

https://github.com/sergiotapia/magnetissimo/wiki/Usage:-Ubuntu-18.04

To install magnetissimo on ubuntu 18.04.4 LTS.

I'm getting this error: ```could not lookup Magnetissimo.Repo because it was not started or it does not exist```.

Any clues what's going on?

**Comment by sxiii** [comment]
Error log:
```
root@oldhack:~/magnetissimo# mix phx.server
[info] Running MagnetissimoWeb.Endpoint with cowboy 2.6.1 at http://localhost:4000

webpack is watching the files…

Browserslist: caniuse-lite is outdated. Please run next command `npm update caniuse-lite browserslist`
Hash: ba638802cc2645a021dd
Version: webpack 4.41.4
Time: 1271ms
Built at: 12/21/2019 7:22:03 PM
                          Asset       Size       Chunks             Chunk Names
                 ../css/app.css    206 KiB  ./js/app.js  [emitted]  ./js/app.js
                 ../favicon.ico   1.23 KiB               [emitted]  
      ../images/magnet-icon.png   37.9 KiB               [emitted]  
../images/magnetissimo-logo.jpg   15.2 KiB               [emitted]  
          ../images/phoenix.png   13.6 KiB               [emitted]  
                  ../robots.txt  202 bytes               [emitted]  
                         app.js   8.26 KiB  ./js/app.js  [emitted]  ./js/app.js
Entrypoint ./js/app.js = ../css/app.css app.js
[0] multi ./js/app.js 28 bytes {./js/app.js} [built]
[../../../deps/phoenix_html/priv/static/phoenix_html.js] /root/magnetissimo/deps/phoenix_html/priv/static/phoenix_html.js 2.17 KiB {./js/app.js} [built]
[./css/app.css] 39 bytes {./js/app.js} [built]
[./js/app.js] 493 bytes {./js/app.js} [built]
    + 2 hidden modules
Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js!css/app.css:
    Entrypoint mini-css-extract-plugin = *
    [./node_modules/css-loader/dist/cjs.js!./css/app.css] 561 bytes {mini-css-extract-plugin} [built]
    [./node_modules/css-loader/dist/cjs.js!./css/bulma.css] 216 KiB {mini-css-extract-plugin} [built]
        + 1 hidden module
[info] GET /
[debug] Processing with MagnetissimoWeb.PageController.index/2
  Parameters: %{}
  Pipelines: [:browser]
[debug] QUERY OK source="torrents" db=1.6ms decode=3.1ms queue=1.9ms
SELECT count('*') FROM "torrents" AS t0 []
[debug] QUERY OK source="torrents" db=2.6ms queue=3.1ms
SELECT t0."id", t0."magnet_url", t0."name", t0."canonical_url", t0."website_source", t0."leechers", t0."seeds", t0."size", t0."published_at", t0."inserted_at", t0."updated_at" FROM "torrents" AS t0 ORDER BY t0."inserted_at" DESC LIMIT $1 OFFSET $2 [50, 0]
[debug] QUERY OK source="torrents" db=1.7ms queue=2.0ms
SELECT t0."website_source", count(t0."id") FROM "torrents" AS t0 GROUP BY t0."website_source" ORDER BY t0."website_source" []
[debug] QUERY OK source="torrents" db=1.6ms queue=1.4ms
SELECT count(t0."id") FROM "torrents" AS t0 []
[info] Sent 200 in 177ms
[debug] [EZTV] Downloading url: https://eztv.io/ezrss.xml
[debug] [ThePirateBay] Downloading url: https://thepiratebay.org/rss//top100/0
[debug] [TorrentDownloads] Downloading url: https://www.torrentdownloads.me/rss.xml?type=today
[debug] [Nyaa] Downloading url: https://nyaa.si/?page=rss
[debug] [NyaaPantsu] Downloading url: https://nyaa.pantsu.cat/feed
[debug] [YTS.am] Downloading url: https://yts.am/rss
[error] GenServer Magnetissimo.Crawlers.ThePirateBay terminating
** (HTTPoison.Error) {:option, :server_only, :honor_cipher_order}
    (httpoison) lib/httpoison.ex:128: HTTPoison.request!/5
    (magnetissimo) lib/crawlers/ThePirateBay.ex:62: Magnetissimo.Crawlers.ThePirateBay.rss/0
    (magnetissimo) lib/crawlers/ThePirateBay.ex:17: Magnetissimo.Crawlers.ThePirateBay.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: :rss_fetch
State: []
[error] GenServer Magnetissimo.Crawlers.YTS terminating
** (HTTPoison.Error) {:option, :server_only, :honor_cipher_order}
    (httpoison) lib/httpoison.ex:128: HTTPoison.request!/5
    (magnetissimo) lib/crawlers/YTS.ex:62: Magnetissimo.Crawlers.YTS.rss/0
    (magnetissimo) lib/crawlers/YTS.ex:17: Magnetissimo.Crawlers.YTS.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: :rss_fetch
State: []
[error] GenServer Magnetissimo.Crawlers.NyaaPantsu terminating
** (HTTPoison.Error) {:option, :server_only, :honor_cipher_order}
    (httpoison) lib/httpoison.ex:128: HTTPoison.request!/5
    (magnetissimo) lib/crawlers/NyaaPantsu.ex:62: Magnetissimo.Crawlers.NyaaPantsu.rss/0
    (magnetissimo) lib/crawlers/NyaaPantsu.ex:17: Magnetissimo.Crawlers.NyaaPantsu.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: :rss_fetch
State: []
[error] GenServer Magnetissimo.Crawlers.EZTV terminating
** (HTTPoison.Error) {:option, :server_only, :honor_cipher_order}
    (httpoison) lib/httpoison.ex:128: HTTPoison.request!/5
    (magnetissimo) lib/crawlers/EZTV.ex:66: Magnetissimo.Crawlers.EZTV.rss/0
    (magnetissimo) lib/crawlers/EZTV.ex:17: Magnetissimo.Crawlers.EZTV.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: :rss_fetch
State: []
[error] GenServer Magnetissimo.Crawlers.TorrentDownloads terminating
** (HTTPoison.Error) {:option, :server_only, :honor_cipher_order}
    (httpoison) lib/httpoison.ex:128: HTTPoison.request!/5
    (magnetissimo) lib/crawlers/TorrentDownloads.ex:72: Magnetissimo.Crawlers.TorrentDownloads.rss/0
    (magnetissimo) lib/crawlers/TorrentDownloads.ex:17: Magnetissimo.Crawlers.TorrentDownloads.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: :rss_fetch
State: []
[error] GenServer Magnetissimo.Crawlers.Nyaa terminating
** (HTTPoison.Error) {:option, :server_only, :honor_cipher_order}
    (httpoison) lib/httpoison.ex:128: HTTPoison.request!/5
    (magnetissimo) lib/crawlers/Nyaa.ex:67: Magnetissimo.Crawlers.Nyaa.rss/0
    (magnetissimo) lib/crawlers/Nyaa.ex:17: Magnetissimo.Crawlers.Nyaa.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: :rss_fetch
State: []
[info] Application magnetissimo exited: shutdown
[info] GET /
[debug] Processing with MagnetissimoWeb.PageController.index/2
  Parameters: %{}
  Pipelines: [:browser]
[info] Sent 500 in 64ms
[error] #PID<0.516.0> running MagnetissimoWeb.Endpoint (connection #PID<0.515.0>, stream id 1) terminated
Server: oldhack:4000 (http)
Request: GET /
** (exit) an exception was raised:
    ** (RuntimeError) could not lookup Magnetissimo.Repo because it was not started or it does not exist
        (ecto) lib/ecto/repo/registry.ex:18: Ecto.Repo.Registry.lookup/1
        (ecto) lib/ecto/repo/queryable.ex:131: Ecto.Repo.Queryable.execute/4
        (ecto) lib/ecto/repo/queryable.ex:18: Ecto.Repo.Queryable.all/3
        (ecto) lib/ecto/repo/queryable.ex:66: Ecto.Repo.Queryable.one/3
        (scrivener_ecto) lib/scrivener/paginater/ecto/query.ex:46: Scrivener.Paginater.Ecto.Query.total_entries/3
        (scrivener_ecto) lib/scrivener/paginater/ecto/query.ex:17: Scrivener.Paginater.Ecto.Query.paginate/2
        (magnetissimo_web) lib/magnetissimo_web/controllers/page_controller.ex:5: MagnetissimoWeb.PageController.index/2
        (magnetissimo_web) lib/magnetissimo_web/controllers/page_controller.ex:1: MagnetissimoWeb.PageController.action/2
        (magnetissimo_web) lib/magnetissimo_web/controllers/page_controller.ex:1: MagnetissimoWeb.PageController.phoenix_controller_pipeline/2
        (magnetissimo_web) lib/magnetissimo_web/endpoint.ex:1: MagnetissimoWeb.Endpoint.instrument/4
        (phoenix) lib/phoenix/router.ex:275: Phoenix.Router.__call__/1
        (magnetissimo_web) lib/magnetissimo_web/endpoint.ex:1: MagnetissimoWeb.Endpoint.plug_builder_call/2
        (magnetissimo_web) lib/plug/debugger.ex:122: MagnetissimoWeb.Endpoint."call (overridable 3)"/2
        (magnetissimo_web) lib/magnetissimo_web/endpoint.ex:1: MagnetissimoWeb.Endpoint.call/2
        (phoenix) lib/phoenix/endpoint/cowboy2_handler.ex:33: Phoenix.Endpoint.Cowboy2Handler.init/2
        (cowboy) /root/magnetissimo/deps/cowboy/src/cowboy_handler.erl:41: :cowboy_handler.execute/2
        (cowboy) /root/magnetissimo/deps/cowboy/src/cowboy_stream_h.erl:296: :cowboy_stream_h.execute/3
        (cowboy) /root/magnetissimo/deps/cowboy/src/cowboy_stream_h.erl:274: :cowboy_stream_h.request_process/3
        (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
[info] Replied phoenix:live_reload :ok
```

**Comment by sergiotapia** [comment]
Closing this stale issue, please feel free to open a new ticket if this happens to you. Thank you!

**Comment by afarazit** [comment]
Still getting this error "(RuntimeError) could not lookup Ecto repo Magnetissimo.Repo because it was not started or it does not exist", running on docker [ef5a9a8](https://github.com/sergiotapia/magnetissimo/commit/ef5a9a87799e8f3314d1e097feb74a51c4392368)
