### ISSUE TITLE
Error first time loading

### ISSUE THREAD

**Issue by RealFascinated** [sergiotapia/magnetissimo#153]
I am a first time user of this and I am running into this issue.

```
16:02:34.332 [info] Migrations already `up`
** (RuntimeError) could not lookup Ecto repo Magnetissimo.Repo because it was not started or it does not exist
    (ecto 3.9.5) lib/ecto/repo/registry.ex:22: Ecto.Repo.Registry.lookup/1
    (ecto 3.9.5) lib/ecto/repo/supervisor.ex:160: Ecto.Repo.Supervisor.tuplet/2
    (magnetissimo 2.0.0) lib/magnetissimo/repo.ex:2: Magnetissimo.Repo.all/2
    (magnetissimo 2.0.0) lib/magnetissimo/db_seeder.ex:5: Magnetissimo.DbSeeder.run/0
    nofile:1: (file)
    (stdlib 4.1.1) erl_eval.erl:748: :erl_eval.do_apply/7
```

**Comment by sergiotapia** [comment]
Whoops sorry about that! This should be fixed with this latest commit. 2b89d42508e323eec2d4f79798ff8eaa1fc2dc9b
