### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by jpcapone** [sergiotapia/magnetissimo#161]
When I type into the Search the seas field the actual search doesn't seem to be completed and I am faced with the screenshot below:
![image](https://user-images.githubusercontent.com/47680328/232232795-af8d3be1-ecac-4aa0-a472-c85f49b3f9ab.png)
Any suggestions?

**Comment by bdruth** [comment]
Same. I don't think anything is getting indexed, either. Admittedly, not sure how that's supposed to work.

**Comment by bdruth** [comment]
#151 fixed this for me

**Comment by askiiart** [comment]
@jpcapone Assuming you're doing this in Docker, stop and remove the container, delete the DB data (the `sources` and `categories` tables, if you don't want to destroy all DB data), and recreate the container(s).

**Comment by cdecompilador** [comment]
I'm having an issue too with search, this is related to the ssl certificate it seems

```
magnetissimo  | 22:17:19.669 [error] Task #PID<0.2745.0> started from #PID<0.2734.0> terminating
magnetissimo  | ** (HTTPoison.Error) {:tls_alert, {:unknown_ca, 'TLS client: In state certify at ssl_handshake.erl:2098 generated CLIENT ALERT: Fatal - Unknown CA\n'}}
magnetissimo  |     (httpoison 2.1.0) lib/httpoison.ex:261: HTTPoison.request!/5
magnetissimo  |     (magnetissimo 2.0.0) lib/magnetissimo/crawlers/yts.ex:21: Magnetissimo.Crawlers.Yts.search/1
magnetissimo  |     (elixir 1.14.4) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
magnetissimo  |     (elixir 1.14.4) lib/task/supervised.ex:34: Task.Supervised.reply/4
magnetissimo  |     (stdlib 4.1.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
magnetissimo  | Function: &:erlang.apply/2
magnetissimo  |     Args: [#Function<0.57527154/1 in Magnetissimo.Torrents.search_torrents/1>, [Magnetissimo.Crawlers.Yts]]
```

Maybe you are having this same error when attempting to search @jpcapone

**Comment by askiiart** [comment]
@cdecompilador Admittedly I haven't run magnetissimo in a long time, pretty much since the last commit, but I think your issue might be unrelated. Not sure, though.

**Comment by sergiotapia** [comment]
Closing due to inactivity.

**Comment by gervisc** [comment]
i have this issue, with the version downloaded today. I used docker compose. This what i see in the logs:`

magnetissimo  | 23:18:00.111 [info] tzdata release in place is from a file last modified Fri, 22 Oct 2021 02:20:47 GMT. Release file on server was last modified Thu, 01 Feb 2024 18:40:48 GMT.
magnetissimo  | 23:18:01.613 [info] Tzdata has updated the release from 2021e to 2024a
magnetissimo  | 23:18:41.133 request_id=F73_Gh9_5EnjJEgAAAAC [info] GET /
magnetissimo  | 23:18:41.179 request_id=F73_Gh9_5EnjJEgAAAAC [info] Sent 200 in 45ms
magnetissimo  | 23:18:41.288 [info] CONNECTED TO Phoenix.LiveView.Socket in 76µs
magnetissimo  |   Transport: :websocket
magnetissimo  |   Serializer: Phoenix.Socket.V2.JSONSerializer
magnetissimo  |   Parameters: %{"_csrf_token" => "N2QgdxQyCAU6NxADWz0AIygmCj5-BA8gCRUZxyeJ_asJ4EWyfrIj-Vhl", "_live_referer" => "undefined", "_mounts" => "0", "_track_static" => %{"0" => "http://192.168.2.6:4000/assets/app-b427e16913eeff5adcd8132199f974bf.css?vsn=d", "1" => "http://192.168.2.6:4000/assets/app-207d38c033d0e6924686f811f7f66992.js?vsn=d"}, "vsn" => "2.0.0"}
magnetissimo  | 23:18:44.346 [info] [Nyaa] Fetching search results page.
magnetissimo  | 23:18:44.346 [info] [YTS] Fetching search results page.
magnetissimo  | 23:18:44.347 [info] [1337x] Fetching search results page.
magnetissimo  | 23:18:44.348 [info] [TorrentDownloads] Fetching search results page.
magnetissimo  | 23:18:44.925 [info] deprecation: parse the HTML with parse_document or parse_fragment before using find/2
magnetissimo  | 23:18:44.940 [info] [Nyaa.si] Creating torrent: I'm in Love with the Villainess - She's so Cheeky for a Commoner v01-02 [Seven Seas] [Stick] (https://nyaa.si/view/1791631)
magnetissimo  | 23:18:45.376 [error] Task #PID<0.2626.0> started from #PID<0.2615.0> terminating
magnetissimo  | ** (HTTPoison.Error) :ehostunreach
magnetissimo  |     (httpoison 2.1.0) lib/httpoison.ex:261: HTTPoison.request!/5
magnetissimo  |     (magnetissimo 2.0.0) lib/magnetissimo/crawlers/yts.ex:21: Magnetissimo.Crawlers.Yts.search/1
magnetissimo  |     (elixir 1.14.4) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
magnetissimo  |     (elixir 1.14.4) lib/task/supervised.ex:34: Task.Supervised.reply/4
magnetissimo  |     (stdlib 4.1.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
magnetissimo  | Function: &:erlang.apply/2
magnetissimo  |     Args: [#Function<0.57527154/1 in Magnetissimo.Torrents.search_torrents/1>, [Magnetissimo.Crawlers.Yts]]
`
