### ISSUE TITLE
Error after upgrading

### ISSUE THREAD

**Issue by NunoHiggs** [sergiotapia/magnetissimo#22]
Hello,

I've upgraded my magnetissimo today, and i got the following error:

**[debug] QUERY ERROR db=28.6ms queue=0.2ms
INSERT INTO "torrents"** ("filesize","leechers","magnet","name","seeders","source","inserted_at","updated_at") VALUES ($1,$2,$3,$4,$5,$6,$7,$8) RETURNING "id" ["1073741824", 0, "magnet:?xt=urn:btih:0XXXXXXXXXXXXXXD1E900&dn=blablabla.torret=udp%3A%2F%2Fopen.demonii.com%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.to%3A2710%2Fannounce&tr=udp%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969%2Fannounce", "blablabla.torrent", 0, "TorrentDownloads", {{2016, 9, 30}, {14, 52, 47, 0}}, {{2016, 9, 30}, {14, 52, 47, 0}}]

[error] Process #PID<0.724.0> raised an exception
**** (CaseClauseError) no case clause matching: {:error, #Ecto.Changeset<action: :insert, changes: %{filesize: "1073741824", leechers: 0, magnet: "magnet:?xt=blablablabla", name: "blabla blabla7", seeders: 0, source: "TorrentDownloads"}, errors: [magnet: {"has already been taken", []}], data: #Magnetissimo.Torrent<>, valid?: false>}
    (magnetissimo) web/models/torrent.ex:51: Magnetissimo.Torrent.save_torrent/1
    (exq) lib/exq/worker/server.ex:119: anonymous fn/3 in Exq.Worker.Server.dispatch_work/2**

The DB is up and running correctly, i see connection.
Other thing that i found is that the images and css's are not loading correctly:

![screen shot 2016-09-30 at 15 59 56](https://cloud.githubusercontent.com/assets/16701703/18996101/f9cdaec6-8726-11e6-9fc1-d39268fe0526.png)

**Comment by NunoHiggs** [comment]
Delete the DB and reinstalled the package and it worked. There must have been something locked somewere.
