### ISSUE TITLE
eztv crashing: (WithClauseError) no with clause matching

### ISSUE THREAD

**Issue by apexo** [sergiotapia/magnetissimo#53]
May or may not be related to #49, #34.

```
[error] GenServer #PID<0.1864.0> terminating
** (WithClauseError) no with clause matching: {:ok, %HTTPoison.Response{body: "<html>\n<head><title>500 Internal Server Error</title></head>\n<body bgcolor=\"white\">\n<center><h1>500 Internal Server Error</h1></center>\n<hr><center>nginx/1.4.6 (Ubuntu)</center>\n</body>\n</html>\n", headers: [{"Date", "Mon, 30 Jan 2017 ..:..:.. GMT"}, {"Content-Type", "text/html"}, {"Transfer-Encoding", "chunked"}, {"Connection", "keep-alive"}, {"Set-Cookie", "__cfduid={…}; expires=Tue, 30-Jan-18 11:26:59 GMT; path=/; domain=.eztv.ag; HttpOnly"}, {"X-Varnish", "{…}"}, {"Age", "1"}, {"Via", "1.1 varnish-v4"}, {"Server", "cloudflare-nginx"}, {"CF-RAY", "{…}"}], status_code: 500}}
    (magnetissimo) lib/crawler/helper.ex:15: Magnetissimo.Crawler.Helper.download/1
    (magnetissimo) lib/crawler/eztv.ex:37: Magnetissimo.Crawler.EZTV.process/2
    (magnetissimo) lib/crawler/eztv.ex:26: Magnetissimo.Crawler.EZTV.handle_info/2
    (stdlib) gen_server.erl:601: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:667: :gen_server.handle_msg/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: :work
State: {[page_link: "https://eztv.ag/page_300", page_link: "https://eztv.ag/page_299", page_link: "https://eztv.ag/page_298", page_link: "https://eztv.ag/page_297", page_link: "https://eztv.ag/page_296", page_link: "https://eztv.ag/page_295", page_link: "https://eztv.ag/page_294", page_link: "https://eztv.ag/page_293", page_link: "https://eztv.ag/page_292", page_link: "https://eztv.ag/page_291", page_link: "https://eztv.ag/page_290", page_link: "https://eztv.ag/page_289", page_link: "https://eztv.ag/page_288", page_link: "https://eztv.ag/page_287", page_link: "https://eztv.ag/page_286", page_link: "https://eztv.ag/page_285", page_link: "https://eztv.ag/page_284", page_link: "https://eztv.ag/page_283", page_link: "https://eztv.ag/page_282", page_link: "https://eztv.ag/page_281", page_link: "https://eztv.ag/page_280", page_link: "https://eztv.ag/page_279", page_link: "https://eztv.ag/page_278", page_link: "https://eztv.ag/page_277", page_link: "https://eztv.ag/page_276", page_link: "https://eztv.ag/page_275", page_link: "https://eztv.ag/page_274", page_link: "https://eztv.ag/page_273", page_link: "https://eztv.ag/page_272", page_link: "https://eztv.ag/page_271", page_link: "https://eztv.ag/page_270", page_link: "https://eztv.ag/page_269", page_link: "https://eztv.ag/page_268", page_link: "https://eztv.ag/page_267", page_link: "https://eztv.ag/page_266", page_link: "https://eztv.ag/page_265", page_link: "https://eztv.ag/page_264", page_link: "https://eztv.ag/page_263", page_link: "https://eztv.ag/page_262", page_link: "https://eztv.ag/page_261", page_link: "https://eztv.ag/page_260", page_link: "https://eztv.ag/page_259", page_link: "https://eztv.ag/page_258", page_link: "https://eztv.ag/page_257", page_link: "https://eztv.ag/page_256", page_link: "https://eztv.ag/page_255", page_link: "https://eztv.ag/page_254", page_link: "https://eztv.ag/page_253", page_link: "https://eztv.ag/page_252", ...], [page_link: "https://eztv.ag/page_1", page_link: "https://eztv.ag/page_2", page_link: "https://eztv.ag/page_3", page_link: "https://eztv.ag/page_4", page_link: "https://eztv.ag/page_5", page_link: "https://eztv.ag/page_6", page_link: "https://eztv.ag/page_7", page_link: "https://eztv.ag/page_8", page_link: "https://eztv.ag/page_9", page_link: "https://eztv.ag/page_10", page_link: "https://eztv.ag/page_11", page_link: "https://eztv.ag/page_12", page_link: "https://eztv.ag/page_13", page_link: "https://eztv.ag/page_14", page_link: "https://eztv.ag/page_15", page_link: "https://eztv.ag/page_16", page_link: "https://eztv.ag/page_17", page_link: "https://eztv.ag/page_18", page_link: "https://eztv.ag/page_19", page_link: "https://eztv.ag/page_20", page_link: "https://eztv.ag/page_21", page_link: "https://eztv.ag/page_22", page_link: "https://eztv.ag/page_23", page_link: "https://eztv.ag/page_24", page_link: "https://eztv.ag/page_25", page_link: "https://eztv.ag/page_26", page_link: "https://eztv.ag/page_27", page_link: "https://eztv.ag/page_28", page_link: "https://eztv.ag/page_29", page_link: "https://eztv.ag/page_30", page_link: "https://eztv.ag/page_31", page_link: "https://eztv.ag/page_32", page_link: "https://eztv.ag/page_33", page_link: "https://eztv.ag/page_34", page_link: "https://eztv.ag/page_35", page_link: "https://eztv.ag/page_36", page_link: "https://eztv.ag/page_37", page_link: "https://eztv.ag/page_38", page_link: "https://eztv.ag/page_39", page_link: "https://eztv.ag/page_40", page_link: "https://eztv.ag/page_41", page_link: "https://eztv.ag/page_42", page_link: "https://eztv.ag/page_43", page_link: "https://eztv.ag/page_44", page_link: "https://eztv.ag/page_45", page_link: "https://eztv.ag/page_46", page_link: "https://eztv.ag/page_47", page_link: "https://eztv.ag/page_48", page_link: "https://eztv.ag/page_49", ...]}
```

**Comment by agustif** [comment]
I haven't touched magnetissimo for a while, a lot of code has changed so I'll try to reproduce the bug...

**Comment by apexo** [comment]
Well, fixing the error is trivial, e.g.:

```
--- a/lib/crawler/helper.ex
+++ b/lib/crawler/helper.ex
@@ -21,6 +21,10 @@ defmodule Magnetissimo.Crawler.Helper do
         Logger.warn "Bad URL!"
         nil

+      {:ok, %HTTPoison.Response{status_code: 500, body: _, headers: _}} ->
+        Logger.warn "500 Internal Server Error on #{url}"
+        nil
+
       {:ok, %HTTPoison.Response{status_code: 502, body: _, headers: _}} ->
         Logger.warn "502 Bad Gateway on #{url}"
         nil
```

But maybe a more generic approach should be implemented, that covers all unexpected status codes.

**Comment by sergiotapia** [comment]
This is fixed on master thanks to @tchoutri :D
