### ISSUE TITLE
[eztv] broken

### ISSUE THREAD

**Issue by nxtreaming** [sergiotapia/magnetissimo#66]
[warn] 404 Page not Found on https://eztv.ag/page_1
[error] GenServer #PID<0.457.0> terminating
** (FunctionClauseError) no function clause matching in Floki.Finder.traverse/4
    lib/floki/finder.ex:61: Floki.Finder.traverse(nil, [], %Floki.Selector{attributes: [], classes: ["epinfo"], combinator: nil, id: nil, namespace: nil, type: "a"}, [])
    lib/floki/finder.ex:73: Floki.Finder.traverse/4
    lib/floki/finder.ex:47: Floki.Finder.find_selectors/2
    (magnetissimo) lib/crawler/eztv.ex:62: Magnetissimo.Crawler.EZTV.torrent_links/1
    (magnetissimo) lib/crawler/eztv.ex:37: Magnetissimo.Crawler.EZTV.process/2
    (magnetissimo) lib/crawler/eztv.ex:26: Magnetissimo.Crawler.EZTV.handle_info/2
    (stdlib) gen_server.erl:601: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:667: :gen_server.handle_msg/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: :work
State: {[page_link: "https://eztv.ag/page_300", page_link: "https://eztv.ag/page_299", page_link: "https://eztv.ag/page_298", page_link: "https://eztv.ag/page_297", page_link: "https://eztv.ag/page_296",
page_link: "https://eztv.ag/page_295", page_link: "https://eztv.ag/page_294", page_link: "https://eztv.ag/page_293", page_link: "https://eztv.ag/page_292", page_link: "https://eztv.ag/page_291", page_link
: "https://eztv.ag/page_290", page_link: "https://eztv.ag/page_289", page_link: "https://eztv.ag/page_288", page_link: "https://eztv.ag/page_287", page_link: "https://eztv.ag/page_286", page_link: "https:
//eztv.ag/page_285", page_link: "https://eztv.ag/page_284", page_link: "https://eztv.ag/page_283", page_link: "https://eztv.ag/page_282", page_link: "https://eztv.ag/page_281", page_link: "https://eztv.ag
/page_280", page_link: "https://eztv.ag/page_279", page_link: "https://eztv.ag/page_278", page_link: "https://eztv.ag/page_277", page_link: "https://eztv.ag/page_276", page_link: "https://eztv.ag/page_275
", page_link: "https://eztv.ag/page_274", page_link: "https://eztv.ag/page_273", page_link: "https://eztv.ag/page_272", page_link: "https://eztv.ag/page_271", page_link: "https://eztv.ag/page_270", page_l
ink: "https://eztv.ag/page_269", page_link: "https://eztv.ag/page_268", page_link: "https://eztv.ag/page_267", page_link: "https://eztv.ag/page_266", page_link: "https://eztv.ag/page_265", page_link: "htt
ps://eztv.ag/page_264", page_link: "https://eztv.ag/page_263", page_link: "https://eztv.ag/page_262", page_link: "https://eztv.ag/page_261", page_link: "https://eztv.ag/page_260", page_link: "https://eztv
.ag/page_259", page_link: "https://eztv.ag/page_258", page_link: "https://eztv.ag/page_257", page_link: "https://eztv.ag/page_256", page_link: "https://eztv.ag/page_255", page_link: "https://eztv.ag/page_
254", page_link: "https://eztv.ag/page_253", page_link: "https://eztv.ag/page_252", ...], [page_link: "https://eztv.ag/page_1", page_link: "https://eztv.ag/page_2", page_link: "https://eztv.ag/page_3", pa
ge_link: "https://eztv.ag/page_4", page_link: "https://eztv.ag/page_5", page_link: "https://eztv.ag/page_6", page_link: "https://eztv.ag/page_7", page_link: "https://eztv.ag/page_8", page_link: "https://e
ztv.ag/page_9", page_link: "https://eztv.ag/page_10", page_link: "https://eztv.ag/page_11", page_link: "https://eztv.ag/page_12", page_link: "https://eztv.ag/page_13", page_link: "https://eztv.ag/page_14"
, page_link: "https://eztv.ag/page_15", page_link: "https://eztv.ag/page_16", page_link: "https://eztv.ag/page_17", page_link: "https://eztv.ag/page_18", page_link: "https://eztv.ag/page_19", page_link: "
https://eztv.ag/page_20", page_link: "https://eztv.ag/page_21", page_link: "https://eztv.ag/page_22", page_link: "https://eztv.ag/page_23", page_link: "https://eztv.ag/page_24", page_link: "https://eztv.a
g/page_25", page_link: "https://eztv.ag/page_26", page_link: "https://eztv.ag/page_27", page_link: "https://eztv.ag/page_28", page_link: "https://eztv.ag/page_29", page_link: "https://eztv.ag/page_30", pa
ge_link: "https://eztv.ag/page_31", page_link: "https://eztv.ag/page_32", page_link: "https://eztv.ag/page_33", page_link: "https://eztv.ag/page_34", page_link: "https://eztv.ag/page_35", page_link: "http
s://eztv.ag/page_36", page_link: "https://eztv.ag/page_37", page_link: "https://eztv.ag/page_38", page_link: "https://eztv.ag/page_39", page_link: "https://eztv.ag/page_40", page_link: "https://eztv.ag/pa
ge_41", page_link: "https://eztv.ag/page_42", page_link: "https://eztv.ag/page_43", page_link: "https://eztv.ag/page_44", page_link: "https://eztv.ag/page_45", page_link: "https://eztv.ag/page_46", page_l
ink: "https://eztv.ag/page_47", page_link: "https://eztv.ag/page_48", page_link: "https://eztv.ag/page_49", ...]}
[info] Application magnetissimo exited: shutdown

**Comment by nxtreaming** [comment]
BTW: how to disable eztv crawl?
