### ISSUE TITLE
undefined function String.trim/1

### ISSUE THREAD

**Issue by leondewey** [sergiotapia/magnetissimo#7]
App starts fine, the UI loads etc etc.

While its processing the feeds I see the following error. 

```
[error] Process #PID<0.5222.0> raised an exception
** (UndefinedFunctionError) undefined function String.trim/1
    (elixir) String.trim("Youtubers Life v0.7.13 Cracked-3DM Verified")
    (magnetissimo) lib/parsers/isohunt.ex:53: Magnetissimo.Parsers.Isohunt.scrape_torrent_information/1
    (magnetissimo) lib/download_worker.ex:88: Magnetissimo.DownloadWorker.perform/3
    (exq) lib/exq/worker/server.ex:119: anonymous fn/3 in Exq.Worker.Server.dispatch_work/2
```

**Comment by leondewey** [comment]
Sorted was on on elixir 1.3+
