### ISSUE TITLE
Does this work on windows?

### ISSUE THREAD

**Issue by seanvree** [sergiotapia/magnetissimo#73]
Got all the deps intalled, but I"m stuck on this error:

```
C:\magnetissimo>mix ecto.create && mix ecto.migrate
Compiling 24 files (.ex)
warning: variable "initial_queue" does not exist and is being expanded to "initial_queue()", please use parentheses to remove the ambiguity or change the variable name
  lib/crawler/thepiratebay.ex:7

warning: variable "initial_queue" does not exist and is being expanded to "initial_queue()", please use parentheses to remove the ambiguity or change the variable name
  lib/crawler/eztv.ex:7

warning: variable "initial_queue" does not exist and is being expanded to "initial_queue()", please use parentheses to remove the ambiguity or change the variable name
  lib/crawler/demonoid.ex:7

warning: variable "initial_queue" does not exist and is being expanded to "initial_queue()", please use parentheses to remove the ambiguity or change the variable name
  lib/crawler/torrentdownloads.ex:7

warning: variable "initial_queue" does not exist and is being expanded to "initial_queue()", please use parentheses to remove the ambiguity or change the variable name
  lib/crawler/leetx.ex:7

warning: variable "initial_queue" does not exist and is being expanded to "initial_queue()", please use parentheses to remove the ambiguity or change the variable name
  lib/crawler/thepiratebay.ex:29

warning: the variable "queue" is unsafe as it has been set inside a case/cond/receive/if/&&/||. Please explicitly return the variable value instead. For example:

    case int do
      1 -> atom = :one
      2 -> atom = :two
    end

should be written as

    atom =
      case int do
        1 -> :one
        2 -> :two
      end

Unsafe variable found at:
  lib/crawler/limetorrents.ex:42

warning: variable "initial_queue" does not exist and is being expanded to "initial_queue()", please use parentheses to remove the ambiguity or change the variable name
  lib/crawler/torrentdownloads.ex:29

warning: variable "initial_queue" does not exist and is being expanded to "initial_queue()", please use parentheses to remove the ambiguity or change the variable name
  lib/crawler/leetx.ex:29

warning: variable "initial_queue" does not exist and is being expanded to "initial_queue()", please use parentheses to remove the ambiguity or change the variable name
  lib/crawler/eztv.ex:29

warning: variable "initial_queue" does not exist and is being expanded to "initial_queue()", please use parentheses to remove the ambiguity or change the variable name
  lib/crawler/demonoid.ex:29

warning: the variable "queue" is unsafe as it has been set inside a case/cond/receive/if/&&/||. Please explicitly return the variable value instead. For example:

    case int do
      1 -> atom = :one
      2 -> atom = :two
    end

should be written as

    atom =
      case int do
        1 -> :one
        2 -> :two
      end

Unsafe variable found at:
  lib/crawler/thepiratebay.ex:32

warning: the variable "queue" is unsafe as it has been set inside a case/cond/receive/if/&&/||. Please explicitly return the variable value instead. For example:

    case int do
      1 -> atom = :one
      2 -> atom = :two
    end

should be written as

    atom =
      case int do
        1 -> :one
        2 -> :two
      end

Unsafe variable found at:
  lib/crawler/torrentdownloads.ex:32

warning: the variable "queue" is unsafe as it has been set inside a case/cond/receive/if/&&/||. Please explicitly return the variable value instead. For example:

    case int do
      1 -> atom = :one
      2 -> atom = :two
    end

should be written as

    atom =
      case int do
        1 -> :one
        2 -> :two
      end

Unsafe variable found at:
  lib/crawler/leetx.ex:32

warning: the variable "queue" is unsafe as it has been set inside a case/cond/receive/if/&&/||. Please explicitly return the variable value instead. For example:

    case int do
      1 -> atom = :one
      2 -> atom = :two
    end

should be written as

    atom =
      case int do
        1 -> :one
        2 -> :two
      end

Unsafe variable found at:
  lib/crawler/eztv.ex:32

warning: the variable "queue" is unsafe as it has been set inside a case/cond/receive/if/&&/||. Please explicitly return the variable value instead. For example:

    case int do
      1 -> atom = :one
      2 -> atom = :two
    end

should be written as

    atom =
      case int do
        1 -> :one
        2 -> :two
      end

Unsafe variable found at:
  lib/crawler/demonoid.ex:32

warning: the variable "queue" is unsafe as it has been set inside a case/cond/receive/if/&&/||. Please explicitly return the variable value instead. For example:

    case int do
      1 -> atom = :one
      2 -> atom = :two
    end

should be written as

    atom =
      case int do
        1 -> :one
        2 -> :two
      end

Unsafe variable found at:
  lib/crawler/torrentdownloads.ex:44

warning: the variable "queue" is unsafe as it has been set inside a case/cond/receive/if/&&/||. Please explicitly return the variable value instead. For example:

    case int do
      1 -> atom = :one
      2 -> atom = :two
    end

should be written as

    atom =
      case int do
        1 -> :one
        2 -> :two
      end

Unsafe variable found at:
  lib/crawler/thepiratebay.ex:44

warning: variable "description" is unused
  lib/crawler/demonoid.ex:78

warning: variable "description" is unused
  lib/crawler/torrentdownloads.ex:89

warning: variable "initial_queue" does not exist and is being expanded to "initial_queue()", please use parentheses to remove the ambiguity or change the variable name
  lib/crawler/worldwidetorrents.ex:7

warning: variable "initial_queue" does not exist and is being expanded to "initial_queue()", please use parentheses to remove the ambiguity or change the variable name
  lib/crawler/worldwidetorrents.ex:29

warning: the variable "queue" is unsafe as it has been set inside a case/cond/receive/if/&&/||. Please explicitly return the variable value instead. For example:

    case int do
      1 -> atom = :one
      2 -> atom = :two
    end

should be written as

    atom =
      case int do
        1 -> :one
        2 -> :two
      end

Unsafe variable found at:
  lib/crawler/worldwidetorrents.ex:32

Generated magnetissimo app
** (Mix) The database for Magnetissimo.Repo couldn't be created: an exception was raised:
    ** (DBConnection.ConnectionError) tcp connect (192.168.1.20:50432): connection refused - :econnrefused
        (db_connection) lib/db_connection/connection.ex:148: DBConnection.Connection.connect/2
        (connection) lib/connection.ex:622: Connection.enter_connect/5
        (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3

03:56:31.469 [error] GenServer #PID<0.402.0> terminating
** (DBConnection.ConnectionError) tcp connect (192.168.1.20:50432): connection refused - :econnrefused
    (db_connection) lib/db_connection/connection.ex:148: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol

C:\magnetissimo>


```

Doesn't matter what port or hostname I put in the dev.exs, it always fails on this.

**Comment by sergiotapia** [comment]
It should work I guess, I don't really use Windows and haven't tested the app on it. It looks like it's a database issue though. Are you sure Postgres is running?

**Comment by seanvree** [comment]
@sergiotapia  - DERP. Db permissions. 

THX.
